---
title: Een geluid uit de bibliotheek toevoegen
hero_image: images/banner.png
description: Hoe voeg je een geluid toe aan je Scratch-sprite
listed: false
copyedit: true
steps:
  - 
    title: Voeg een geluid toe aan je sprite
