title: generic-scratch3-sound-from-library
hero_image: images/banner.png
description: generic-scratch3-sound-from-library description
version: 4
listed: false
copyedit: false
last_tested: "2018-10-23"
steps:
  - title: Introduction
  - title: What you will need
  - title: Step title
