---
title: Legge til en lyd fra biblioteket
hero_image: images/banner.png
description: Slik legger du til en lyd på en Scratch-figur
listed: false
copyedit: true
steps:
  - title: Legg til en lyd på figuren din
