---
title: Thêm âm thanh từ thư viện
hero_image: images / banner.png
description: Cách thêm âm thanh vào sprite Scratch của bạn
listed: false
copyedit: true
steps:
  - 
    title: Add a sound to your sprite
