---
title: Tilføjelse af en lyd fra biblioteket
hero_image: images/banner.png
description: Sådan tilføjes en lyd til din Scratch-sprite
listed: false
copyedit: true
steps:
  - title: Tilføj en lyd til din sprite
