---
title: Adicionar um som da biblioteca
hero_image: images/banner.png
description: Como adicionar um som ao teu actor do Scratch
listed: false
copyedit: true
steps:
  - title: Adiciona um som ao teu actor
