---
title: A침adir un sonido de la biblioteca
hero_image: images/banner.png
description: C칩mo a침adir un sonido a tu sprite de Scratch
listed: false
copyedit: true
steps:
  - 
    title: A침adir un sonido a tu sprite
