---
title: Ychwanegu sain o'r llyfrgell
hero_image: images/banner.png
description: Sut i ychwanegu sain at dy gorlun Scratch
listed: false
copyedit: true
steps:
  - title: Ychwanegu sain at dy gorlun
