---
title: Hinzufügen von einem Klang aus der Bibliothek
hero_image: images/banner.png
description: So wird ein Klang zu deiner Scratch-Figur hinzugefügt
listed: false
copyedit: true
steps:
  - 
    title: Füge deiner Figur einen Klang hinzu
