---
title: Füge einen Klang aus der Bibliothek hinzu
hero_image: images/banner.png
description: So wird ein Klang deiner Scratch-Figur hinzugefügt
listed: false
copyedit: true
steps:
  - 
    title: Füge deiner Figur einen Klang hinzu
