---
title: Adăugarea unui sunet din bibliotecă
hero_image: images/banner.png
description: Cum să adaugi un sunet personajului tău Scratch
listed: false
copyedit: true
steps:
  - 
    title: Adaugă un sunet personajului
