---
title: Adăugarea unui sunet din bibliotecă
hero_image: images/banner.png
description: Cum să asociați un sunet unui personaj Scratch
listed: false
copyedit: true
steps:
  - 
    title: Asociați un sunet personajului
