---
title: Adăugarea unui sunet din bibliotecă
hero_image: images/banner.png
description: Cum să asociezi un sunet personajului tău Scratch
listed: false
copyedit: true
steps:
  - title: Asociază un sunet personajului
