---
title: Adicionando um som da biblioteca
hero_image: images/banner.png
description: Como adicionar um som para o seu ator Scratch
listed: false
copyedit: true
steps:
  - 
    title: Adicione um som para o seu ator
