---
title: Menambahkan suara dari pustaka
hero_image: images/banner.png
description: Cara menambahkan suara ke sprite Scratch milikmu
listed: false
copyedit: true
steps:
  - 
    title: Menambahkan suara ke sprite milikmu
