---
title: Menambahkan sebuah suara dari pustaka
hero_image: images/banner.png
description: Cara menambahkan suara ke sprite Scratch Kamu
listed: false
copyedit: true
steps:
  - 
    title: Menambahkan sebuah suara ke sprite Kamu
