---
title: Afegint un so de la biblioteca
hero_image: images/banner.png
description: Com afegir un so al teu personatge de Scratch
listed: false
copyedit: true
steps:
  - 
    title: Afegeix un so al teu personatge
