---
title: ಗ್ರಂಥಾಲಯದಿಂದ ಧ್ವನಿಯನ್ನು ಸೇರಿಸುವುದು
hero_image: images/banner.png
description: ನಿಮ್ಮ scratch spriteಗೆ ಧ್ವನಿಯನ್ನು ಹೇಗೆ ಸೇರಿಸುವುದು
listed: false
copyedit: true
steps:
  - 
    title: ನಿಮ್ಮ spriteಗೆ ಧ್ವನಿ ಸೇರಿಸಿ
