---
title: Dodawanie dźwięku z biblioteki
hero_image: images/banner.png
description: Jak dodać dźwięk do duszka w Scratchu
listed: false
copyedit: true
steps:
  - title: Dodaj dźwięk do twojego duszka
