---
title: Pridanie zvuku z knižnice
hero_image: images/banner.png
description: Ako pridať zvuk tvojej postave v jazyku Scratch
listed: false
copyedit: true
steps:
  - 
    title: Pridaj tvojej postave zvuk
