---
title: Προσθέτοντας ένα ήχο από τη βιβλιοθήκη
hero_image: images/banner.png
description: Πώς να προσθέσεις έναν ήχο στο αντικείμενο Scratch
listed: false
copyedit: true
steps:
  - title: Πρόσθεσε έναν ήχο στο αντικείμενό σου
