---
title: Ajouter un son depuis la bibliothèque
hero_image: images/banner.png
description: Comment ajouter un son à ton lutin de Scratch
listed: false
copyedit: true
steps:
  - 
    title: Ajoute un son à ton lutin
