---
title: Aggiungere un suono dalla libreria
hero_image: images/banner.png
description: Come aggiungere un suono al tuo sprite di Scratch
listed: false
copyedit: true
steps:
  - title: Aggiungi un suono al tuo sprite
